spring.application.name=Backend_pi
### DATABASE ###
server.port=8083
spring.datasource.url=jdbc:mysql://localhost:3306/syncra?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=true 
spring.jpa.hibernate.ddl-auto=update
moderation.service.url=http://localhost:5001
moderation.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=10.227.115.152