server.port=8090
spring.application.name=api-gateway
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# ? AJOUTER cette ligne ? active le load balancer
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# PI_MS5 ? adresse directe sans lb://
spring.cloud.gateway.routes[2].id=ms5
spring.cloud.gateway.routes[2].uri=http://localhost:8085
spring.cloud.gateway.routes[2].predicates[0]=Path=/ms5/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# BACKEND_PI ? adresse directe
spring.cloud.gateway.routes[0].id=backend
spring.cloud.gateway.routes[0].uri=http://10.227.115.152:8083
spring.cloud.gateway.routes[0].predicates[0]=Path=/backend/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# MS-PROJETS ? adresse directe
spring.cloud.gateway.routes[1].id=projets
spring.cloud.gateway.routes[1].uri=http://10.227.115.41:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/projets/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# PROJETPI ? adresse directe
spring.cloud.gateway.routes[3].id=projetpi
spring.cloud.gateway.routes[3].uri=http://10.227.115.9:8082
spring.cloud.gateway.routes[3].predicates[0]=Path=/projetpi/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

# EVENT-SERVICE
spring.cloud.gateway.routes[4].id=event
spring.cloud.gateway.routes[4].uri=http://10.227.115.192:8089
spring.cloud.gateway.routes[4].predicates[0]=Path=/event/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1

#  AJOUT� : MS6-E-COMMERCE
spring.cloud.gateway.routes[5].id=ecommerce
spring.cloud.gateway.routes[5].uri=http://10.227.115.79:8086
spring.cloud.gateway.routes[5].predicates[0]=Path=/ecommerce/**
spring.cloud.gateway.routes[5].filters[0]=StripPrefix=1